[workspace]
members = [
    "client",
    "server",
    "shared"
]
resolver = "2"

[workspace.dependencies]
# Ortak dependencies
tfhe = { version = "0.9", features = ["boolean", "x86_64"] }
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"